### ISSUE TITLE
kraus has no license

### ISSUE THREAD

**Issue by toke** [jautz/kraus#1]

**Comment by jautz** [comment]
Thanks for the hint. We should discuss this issue in KRAUS and determine an appropriate licence together.

**Comment by jautz** [comment]
The discussion in our lunch break did not produce a unanimous resolution. The usual suspects of [FLOSS licenses](http://en.wikipedia.org/wiki/Category:Free_and_open-source_software_licenses) have been brought up: Apache, Artistic, BSD, GNU, Mozilla.
So your benevolent dictator has made up his mind and licensed K.R.A.U.S. under the Apache License, Version 2.0.

**Comment by jautz** [comment]
Message to my future self: With [choosealicense.com](http://choosealicense.com/) there is a good starting point helping developers to choose the license that fits to their requirements / ideals.

What I like about the Apache License 2.0 is that it seems to offer [the best patent protections among the permissive licenses](http://ebb.org/bkuhn/blog/2010/06/30/bilski.html) -- article found via [software patents wiki](http://en.swpat.org/wiki/Patent_clauses_in_software_licences).
